[profile.default]
src = "src"
out = "out"
libs = ["lib"]
isolate = true
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 999_999
evm_version = "cancun"
ignored_error_codes = ["transient-storage"]
bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 1_000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
